[package]
name = "Lending"
version = "1.0.0"
authors = []

[addresses]
lending = "0x3dc5ef372359b6ab006bb517a8df5ca1b2c8ef35ce1ff45f7db8a44e2e43e856"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
